# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7qUWHWkzBSQUvJLshRNbO541DMDN2HV
"""

tasks = []

def add_task(task):
    tasks.append(task)
    print(f"Task added: '{task}'")

def view_tasks():
    if not tasks:
        print("Your to-do list is empty!")
    else:
        print("\n Your To-Do List:")
        for i, task in enumerate(tasks, 1):
            print(f"  {i}. {task}")
    print()

def main():
    print("Welcome to the Magic To-Do List!\n")

    while True:
        print("What would you like to do?")
        print("  1. Add a task")
        print("  2. View all tasks")
        print("  3. Quit")

        choice = input("\nEnter your choice (1/2/3): ").strip()

        if choice == "1":
            task = input("Enter your task: ").strip()
            if task:
                add_task(task)
            else:
                print("Task cannot be empty!")

        elif choice == "2":
            view_tasks()

        elif choice == "3":
            print("Goodbye!")
            break

        else:
            print("Invalid choice. Please enter 1, 2, or 3.\n")

main()